#! /bin/sh

tint2 &

xrandr -s 1360x768 &

setxkbmap es &

volumeicon &

nm-applet &

gtk-update-icon-cache sleep 0.5 &

xsetroot -cursor_name left_ptr &

xrdb -load ~/.config/X11/xresources &

xmodmap ~/.config/X11/xmodmap &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
